version: '3'
services:
  web:
    image: tuusuario/miapp:v1.0 #reemplazar por tu usuario
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
    environment:
      - FLASK_ENV=development